services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - frontend
      - ai
      # - backend
    networks:
      - app_network
    restart: always

  frontend:
    build: ./FE
    expose:
      - "5173"
    volumes:
      - ./FE:/FE
      - /FE/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network
    restart: always

  backend:
    build: ./BE/undaid
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/undaied?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/undaied?useSSL=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app_network
    restart: always

  ai:
    build: ./AI
    expose:
      - "8000"
    volumes:
      - ./AI:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - app_network
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
    restart: always

volumes:
  nginx_logs:
  mysql_data:

networks:
  app_network:
    driver: bridge